### ISSUE TITLE
license infringement

### ISSUE THREAD

**Issue by fzaninotto** [Kirk-Wang/react-admin.com#20]
Hi ! I've seen that you've translated the react-admin documentation to Chinese. Thanks for the effort.

However, you've also copied the English version and changed le license, which is legally an infraction. Also, as your English pages copy the same content as the ones from http://marmelab.com/react-admin, Google penalizes both your website and ours in its search result. 

Could you please add a canonical meta tag to the English version of the doc pointing to our site, and include the marmelab copyright in the license?

Also, we would appreciate a link to the main react-admin website and a mention that yours is a community effort to translate the documentation.

**Comment by Kirk-Wang** [comment]
@fzaninotto Sorry!!!
I will update license.

**Comment by Kirk-Wang** [comment]
@fzaninotto I've already update it..
